### ISSUE TITLE
Update UI of Game Screen

### ISSUE THREAD

**Issue by Zambrella** [Flutter-Buddies/tic_tac_no#10]
Apply styling and UI improvements to game screen in line with styling of menu screen.

**Comment by slovnicki** [comment]
this work shall be done at `game` branch

**Comment by Zambrella** [comment]
<img width="470" alt="Screenshot 2020-12-06 at 19 35 34" src="https://user-images.githubusercontent.com/53582591/101290440-44c45000-37fa-11eb-9b83-7fbaad7ea1c5.png">
This is my mockup for the game screen. Time to start coding.

**Comment by slovnicki** [comment]
Nice! I like it a lot :smiley:
