### ISSUE TITLE
Game Rules and Walkthrough

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/tic_tac_no#13]
Make a screen with those information, animations, demos, etc.

**Comment by slovnicki** [comment]
https://pub.dev/packages/introduction_screen

**Comment by slovnicki** [comment]
1. You’re faced with a tic-tac-toe board you must win.
<image of regular tic tac toe, but  big, the size of our main grid. You’ll see in next step why this is important>

2. But there’s a catch; each square is a tic-tac-toe board!
<image of real grid fades in, i.e. InnerGrids start showing up>

3. You must win the inner grid to claim this position on main grid. Once you claim it, no one can claim it again.
<the same image as before, just one random InnerGrid highlighted in the state of wining move for that InnerGrid>

4. Easy? There’s one more thing; your move within InnerGird determines in which InnerGrid can your opponent play
<image of grid with highlighted last move and arrow pointing to next playable InnerGrid>

5. good luck

**Comment by Zambrella** [comment]
This has been added.
