### ISSUE TITLE
Fix overflow of triangle piece

### ISSUE THREAD

**Issue by Zambrella** [Flutter-Buddies/tic_tac_no#26]

**Comment by Zambrella** [comment]
![Screenshot_1612519274](https://user-images.githubusercontent.com/53582591/107019023-167ed480-6799-11eb-8428-4dcdd128d180.png)
Fixed by changing the `strokeJoin` property on the painter to `StrokeJoin.round` - https://api.flutter.dev/flutter/dart-ui/StrokeJoin-class.html

**Comment by slovnicki** [comment]
Nice!
