### ISSUE TITLE
More clearer AI selection menu

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/tic_tac_no#28]
Just so it's obvious that AI strength can be chosen

**Comment by Zambrella** [comment]
<img width="646" alt="Screenshot 2021-01-26 at 16 01 16" src="https://user-images.githubusercontent.com/53582591/105869992-b9905b00-5fef-11eb-8d08-e7065296b62c.png">
Done and pushed. Not the most elegant and would be good to have some animation but it's functional and clear that it can be changed.
