### ISSUE TITLE
Create a strike through the boards to show the winning three

### ISSUE THREAD

**Issue by joeyda3rd** [Flutter-Buddies/tic_tac_no#38]
On both the big and little boards, draw a line through the cells to show what 3 are the winning moves.

![image](https://user-images.githubusercontent.com/3943508/107860164-c98ba580-6e0b-11eb-8095-abd0e879f2c3.png)

**Comment by Zambrella** [comment]
Uploading Screen Recording 2021-02-25 at 11.10.19.mov…

This was A LOT more complicated than I had anticipated. Would appreciate someone (@slovnicki) taking a look to make sure I haven't made any major errors (I have tested).

I would also be interested to know if there was a better way of doing this. This update has been pushed into the main branch.

**Comment by Zambrella** [comment]
https://user-images.githubusercontent.com/53582591/109145444-662e3b80-775a-11eb-816f-cad39e14f42b.mov

**Comment by slovnicki** [comment]
I'll check it out, definitely before Sat 17:30 so I can share my thoughts then

**Comment by joeyda3rd** [comment]
This looks good! Because I like to add complexity, I also think it would be nice to have it on the mini-boards too.

**Comment by slovnicki** [comment]
> This looks good! Because I like to add complexity, I also think it would be nice to have it on the mini-boards too. 

I agree with @joeyda3rd about mini-boards 😁

**Comment by Zambrella** [comment]
I feel like it might get a bit cluttered if we do all the mini-boards too? That's my gut reaction anyway.

**Comment by mzdm** [comment]
Maybe a short animation of a line that would disappear afterward on that mini-board? But I think that would be hard to pull that off 😃
