### ISSUE TITLE
SettingsScreen UI

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/tic_tac_no#4]
Make settings screen for setting the player names, colors, game type, opponent AI player difficulty, ...

**Comment by Zambrella** [comment]
Thinking about it, I think it would make more sense to have the settings about the game you're about to play to be a modal that opens when you click play. How do you feel about that @slovnicki ? I'm going to draw up some wireframes now as I find it easier to get an idea of what to code.

**Comment by slovnicki** [comment]
@Zambrella I like the idea. I agree; it would feel better to have a modal. Go for it.
Looking forward to sketches.

**Comment by Zambrella** [comment]
<img width="970" alt="Screenshot 2020-11-22 at 11 26 18" src="https://user-images.githubusercontent.com/53582591/99902413-8c54c300-2cb5-11eb-9de2-45905acdf885.png">

Going to add some colour/styling now

**Comment by Zambrella** [comment]
Here's a link to the prototype - https://www.figma.com/proto/q0xwspVrjoOafwxKrHECKw/Tic-Tac-No?node-id=1%3A2&viewport=-397%2C351%2C1.3991155624389648&scaling=scale-down 

If you've not used Figma before just click somewhere in the screen and it will highlight what can be clicked.

Let me know what you think in terms of the flow and content. Not super set on the colours but you get the idea.

**Comment by Zambrella** [comment]
<img width="588" alt="Screenshot 2020-11-22 at 21 07 04" src="https://user-images.githubusercontent.com/53582591/99917214-bb475500-2d06-11eb-93ee-4f3c6641e738.png">
Just done the home screen. Going to work on bottom sheet next.

**Comment by slovnicki** [comment]
@Zambrella I would rather we have the menu in this order:
- Single Player
- Local Multiplayer
- Online Multiplayer

Seems more natural to me.

**Comment by Zambrella** [comment]
> @Zambrella I would rather we have the menu in this order:
> 
> * Single Player
> * Local Multiplayer
> * Online Multiplayer
> 
> Seems more natural to me.

Sure thing

**Comment by slovnicki** [comment]
I'll close this issue now and we'll continue the development from other issues.
