### ISSUE TITLE
[Bug] Landscape is not usable

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Flutter-Buddies/tic_tac_no#41]
I believe we should limit the orientations to only portrait mode until we find a way to make landscape be user friendly since in landscape you can scroll, just view some of the UI.

If you believe that we need to restrict to only portrait up and portrait down I can file a PR to fix the bug.

<img src="https://user-images.githubusercontent.com/41989385/107861447-c5d14080-6e56-11eb-9a0c-4ef4162e8e64.png" width="350px" /><img src="https://user-images.githubusercontent.com/41989385/107861448-c7026d80-6e56-11eb-9a9f-5d57cbcf5cc2.png" width="200px" />

**Comment by slovnicki** [comment]
Yes, restrict it to only portrait mode
