### ISSUE TITLE
[Feature] Localize/Internationalize app

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Flutter-Buddies/tic_tac_no#42]
I would like to suggest adding support for more translations in the app.

I can do Arabic since it is my native language and it won't be a Google Translate quality one 😉🤣.

I propose using `easy_localization` package which is maintained so well. I even used it in some of my apps.
package link: https://pub.dev/packages/easy_localization

An app that will be really useful and is open source is this app for generating JSON needed for the package to work.
GitHub repo link: https://github.com/gilmarsquinelato/i18n-manager

Those are really good from my own experience, I use them personally in my apps.

**Comment by slovnicki** [comment]
Sure, go for it! 🚀

**Comment by YazeedAlKhalaf** [comment]
I suggest changing from asap font to one of those:

- https://fonts.google.com/specimen/Tajawal?preview.text=%D8%AA%D9%8A%D9%83%20%D8%AA%D8%A7%D9%83%20%D9%86%D9%88%20Tic%20Tac%20No&preview.text_type=custom
- https://fonts.google.com/specimen/Cairo?preview.text=%D8%AA%D9%8A%D9%83%20%D8%AA%D8%A7%D9%83%20%D9%86%D9%88%20Tic%20Tac%20No&preview.text_type=custom

**Comment by Zambrella** [comment]
@YazeedAlKhalaf Cairo font looks best to me, although I'd like to leave the title of `Tic-Tac-No` in a monospace font. Are these font changes included in the pull request?

**Comment by YazeedAlKhalaf** [comment]
Still I wrote here to discuss and see what we decide so the I can do the commits, it is still WIP

Okay will let the tic tac toe be mono scape, other text will Cairo.

It will be just and if statement.

**Comment by YazeedAlKhalaf** [comment]
@Zambrella Just added the fonts to the pull request, you can try it in my fork branch `add_arabic_language`
