### ISSUE TITLE
[Bug] Shapes can be a bit big on larger screens

### ISSUE THREAD

**Issue by Zambrella** [Flutter-Buddies/tic_tac_no#44]
![Screenshot_20210213_204812](https://user-images.githubusercontent.com/53582591/107861995-86e4c000-6e41-11eb-9bd2-1571256458ef.jpg)

**Comment by Zambrella** [comment]
![Screenshot 2021-02-14 at 11 37 57](https://user-images.githubusercontent.com/53582591/107875649-17aab280-6eb9-11eb-8bbf-c86cce7cbdf4.png)
![Screenshot 2021-02-14 at 11 39 40](https://user-images.githubusercontent.com/53582591/107875701-55a7d680-6eb9-11eb-9fa3-526caef2781c.png)

Tidied it up a bit using `FractionallySizedBox` and `AspectRatio`.

**Comment by slovnicki** [comment]
Is this a typo? "Player 1 win", but "Player 2 wins"

**Comment by Zambrella** [comment]
It's a bug, I think there's an error with the logic but I wasn't going to bother fixing it here because when we do the new game end pop up I'll fix it there (or someone else 😝)
