### ISSUE TITLE
💡 Use linting

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Flutter-Buddies/tic_tac_no#47]
I suggest using linting to make sure the code is consistent. There are a lot of libraries to choose from so if you suggest one list some pros and cons if available.

**Comment by slovnicki** [comment]
I propose [pedantic](https://github.com/google/pedantic) without `omit_local_variable_types`

**Comment by slovnicki** [comment]
Also we should check this: https://pub.dev/packages/lint

**Comment by Abhishek01039** [comment]
we should try lint!

**Comment by mzdm** [comment]
> I propose [pedantic](https://github.com/google/pedantic) without `omit_local_variable_types`

I second this 👍
