### ISSUE TITLE
AI plays on boards where there was already a winner

### ISSUE THREAD

**Issue by Tahaan** [Flutter-Buddies/tic_tac_no#54]
Once a board has a winner the AI should no longer keep placing it's pieces on that board

**Comment by slovnicki** [comment]
What exactly do you mean? Can you give a screenshot?

**Comment by Tahaan** [comment]
After winning the inner board, the AI continues playing on that same inner board.  I will record a video.

**Comment by slovnicki** [comment]
@Tahaan that's normal. Inner grid can be played at if there exist empty cells, no matter if the inner grid is won or not.
It can be a great tactic to send opponent to already won inner grids, because nothing can be changed there and you basically get free moves.

**Comment by Tahaan** [comment]
OK, closing the issue as that is the expected behaviour.
