### ISSUE TITLE
es.json contains invalid Json causing easy_localization:generate to baulk

### ISSUE THREAD

**Issue by Tahaan** [Flutter-Buddies/tic_tac_no#55]
The file contains "comments" which the easy_localization:generate trips up over.

**Comment by slovnicki** [comment]
@Goober0329

**Comment by Goober0329** [comment]
So is the issue closed now? Do I need to make any changes?

**Comment by slovnicki** [comment]
Yes, he removed the comments. It was done after I tagged you so... sorry 🙂

**Comment by Goober0329** [comment]
haha no worries!

**Comment by Tahaan** [comment]
Fixed by PR #56 (Merged commit 3483fcc)
