### ISSUE TITLE
AF translation tweak

### ISSUE THREAD

**Issue by slovnicki** [Flutter-Buddies/tic_tac_no#58]
@Tahaan is it possible to make the translation `"how_to_play": "Hoe om te speel",` a little bit shorter?
If not, we're gonna need to adjust the UI a bit.

![Screenshot from 2021-02-17 14-34-06](https://user-images.githubusercontent.com/29288059/108211635-36b17a80-712d-11eb-8052-141585aae894.png)

**Comment by Tahaan** [comment]
I can think of other ways to say it that has similar-ishmeaning:

a) "Spel hulp" (Help with the game)
b) "Hulp" (Help)
c) "Inligting" (Information)

These are in order of preferences.

**Comment by slovnicki** [comment]
I would go with a)
Can you make another PR with that change?
