### ISSUE TITLE
Language settings - scrollbar indicator

### ISSUE THREAD

**Issue by mzdm** [Flutter-Buddies/tic_tac_no#79]
Now that there are more languages it would be nice to show some kind of indicator that there are more of them.

Something what I mean:
<p align="center">
<img height="auto" width="auto" src="https://user-images.githubusercontent.com/67197047/110466917-a84e6a00-80d6-11eb-96be-0fdc038006bf.png" />
<img height="auto" width="auto" src="https://user-images.githubusercontent.com/67197047/110467801-bb156e80-80d7-11eb-9203-8b326a63ef99.png" />
</p>

**Comment by slovnicki** [comment]
I definitely agree

**Comment by mzdm** [comment]
![scroll](https://user-images.githubusercontent.com/67197047/110507130-0a6f9500-8100-11eb-8e9b-fe5024903990.gif)

what about this ? didn't test it on smaller screens yet

**Comment by Zambrella** [comment]
This looks great. Look forward to seeing the code you used to achieve this.
