### ISSUE TITLE
App size reduction

### ISSUE THREAD

**Issue by mzdm** [Flutter-Buddies/tic_tac_no#80]
I think this is a recently added thing to Devtools - measure & analyze apk size.

I've run the analyzer and these are the results:
![image](https://user-images.githubusercontent.com/67197047/110471984-185fee80-80dd-11eb-9998-bd46bae33179.png)

I think there can be achieved ~1-1,5MB size reduction by compressing asset images and sounds without losing noticeable qualities.

**Comment by slovnicki** [comment]
I agree

**Comment by Zambrella** [comment]
I have updated the audio files to mp3 which should cut down on the app size significantly. However, audio is now not working which I am looking in to.

**Comment by mzdm** [comment]
> I have updated the audio files to mp3 which should cut down on the app size significantly. However, audio is now not working which I am looking in to.

the previous format was .wav, maybe it must be the same?

**Comment by Zambrella** [comment]
mp3 is supported but I kept the names the same which has maybe confused it. I did do a Flutter clean and uninstalled the app. We'll see...

**Comment by Zambrella** [comment]
For whatever reason the app doesn't like the mp3s I created. Maybe a weird bitrate or something. Will try again.

**Comment by Zambrella** [comment]
<img width="1419" alt="Screenshot 2021-03-24 at 11 29 42" src="https://user-images.githubusercontent.com/53582591/112303474-3bb99a80-8c94-11eb-9961-c618badb88db.png">
Size has gone from 2.4MB to 0.37MB which is about a 600% decrease in asset size :)
I did this by converting audio files to mp3 and compressing the 'how to play' images.

**Comment by mzdm** [comment]
> <img alt="Screenshot 2021-03-24 at 11 29 42" width="1419" src="https://user-images.githubusercontent.com/53582591/112303474-3bb99a80-8c94-11eb-9961-c618badb88db.png">
> 
> Size has gone from 2.4MB to 0.37MB which is about a 600% decrease in asset size :) I did this by converting audio files to mp3 and compressing the 'how to play' images.

Nice! 🤯
